server:
  port: 8762
spring:
  application:
    name: shopcart-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#zuul:
#  SendResponseFilter:
#    post:
#      disable: true